const words = [
  { english: "have", russian: "иметь" },

  { english: "that", russian: "что" },

  { english: "be", russian: "быть" },
  { english: "this", russian: "это" },
  { english: "from", russian: "из" },
  { english: "or", russian: "или" },
  { english: "one", russian: "один" },
  { english: "had", russian: "имел" },
  { english: "by", russian: "по" },
  { english: "word", russian: "слово" },
  { english: "will", russian: "будет" },
  { english: "say", russian: "сказать" },
  { english: "who", russian: "кто" },
  { english: "one", russian: "один" },
  { english: "time", russian: "время" },
  { english: "out", russian: "вне" },
  { english: "about", russian: "о" },
  { english: "many", russian: "много" },
  { english: "would", russian: "бы" },
  { english: "make", russian: "делать" },
  { english: "like", russian: "нравиться" },
  { english: "him", russian: "его" },
  { english: "into", russian: "в" },
  { english: "time", russian: "время" },
  { english: "has", russian: "имеет" },
  { english: "more", russian: "больше" },
  { english: "no", russian: "нет" },
  { english: "such", russian: "такой" },
  { english: "up", russian: "вверх" },
  { english: "out", russian: "вне" },
  { english: "other", russian: "другой" },
  { english: "some", russian: "некоторые" },
  { english: "could", russian: "мог бы" },
  { english: "two", russian: "два" },
  { english: "see", russian: "видеть" },
  { english: "than", russian: "чем" },
  { english: "first", russian: "первый" },
  { english: "been", russian: "был" },
  { english: "now", russian: "сейчас" },
  { english: "down", russian: "вниз" },
  { english: "get", russian: "получить" },
  { english: "come", russian: "приходить" },
  { english: "made", russian: "сделал" },
  { english: "may", russian: "может" },
  { english: "part", russian: "часть" },
  { english: "over", russian: "над" },
  { english: "new", russian: "новый" },
  { english: "take", russian: "брать" },
  { english: "only", russian: "только" },
  { english: "little", russian: "маленький" },
  { english: "work", russian: "работа" },
  { english: "know", russian: "знать" },
  { english: "place", russian: "место" },
  { english: "year", russian: "год" },
  { english: "live", russian: "жить" },
  { english: "me", russian: "меня" },
  { english: "back", russian: "назад" },
  { english: "give", russian: "давать" },
  { english: "most", russian: "большинство" },
  { english: "very", russian: "очень" },
  { english: "after", russian: "после" },
  { english: "thing", russian: "вещь" },
  { english: "our", russian: "наш" },
  { english: "just", russian: "просто" },
  { english: "name", russian: "имя" },
  { english: "good", russian: "хороший" },
  { english: "sentence", russian: "предложение" },
  { english: "great", russian: "великий" },
  { english: "say", russian: "сказать" },
  { english: "help", russian: "помощь" },
  { english: "through", russian: "через" },
  { english: "much", russian: "много" },
  { english: "before", russian: "до" },
  { english: "right", russian: "право" },
  { english: "too", russian: "слишком" },
  { english: "mean", russian: "значить" },
  { english: "old", russian: "старый" },
  { english: "any", russian: "любой" },
  { english: "same", russian: "тот же" },
  { english: "tell", russian: "рассказать" },
  { english: "set", russian: "набор" },
  { english: "three", russian: "три" },
  { english: "want", russian: "хотеть" },
  { english: "air", russian: "воздух" },
  { english: "well", russian: "хорошо" },
  { english: "also", russian: "также" },
  { english: "play", russian: "играть" },
  { english: "small", russian: "маленький" },
  { english: "end", russian: "конец" },
  { english: "put", russian: "положить" },
  { english: "home", russian: "дом" },
  { english: "read", russian: "читать" },
  { english: "hand", russian: "рука" },
  { english: "port", russian: "порт" },
  { english: "large", russian: "большой" },
  { english: "spell", russian: "заклинание" },
  { english: "add", russian: "добавить" },
  { english: "even", russian: "даже" },
  { english: "land", russian: "земля" },
  { english: "here", russian: "здесь" },
  { english: "must", russian: "должен" },
  { english: "big", russian: "большой" },
  { english: "high", russian: "высокий" },
  { english: "such", russian: "такой" },
  { english: "follow", russian: "следовать" },
  { english: "act", russian: "действовать" },
  { english: "why", russian: "почему" },
  { english: "ask", russian: "спросить" },
  { english: "men", russian: "мужчины" },
  { english: "change", russian: "изменить" },
  { english: "went", russian: "ушел" },
  { english: "light", russian: "свет" },
  { english: "kind", russian: "вид" },
  { english: "off", russian: "выключить" },
  { english: "need", russian: "нуждаться" },
  { english: "house", russian: "дом" },
  { english: "picture", russian: "картина" },
  { english: "try", russian: "попробовать" },
  { english: "us", russian: "нас" },
  { english: "again", russian: "снова" },
  { english: "animal", russian: "животное" },
  { english: "point", russian: "точка" },
  { english: "mother", russian: "мать" },
  { english: "world", russian: "мир" },
  { english: "near", russian: "близко" },
  { english: "build", russian: "строить" },
  { english: "self", russian: "я сам" },
  { english: "earth", russian: "земля" },
  { english: "father", russian: "отец" },
  { english: "head", russian: "голова" },
  { english: "stand", russian: "стоять" },
  { english: "own", russian: "собственный" },
  { english: "page", russian: "страница" },
  { english: "should", russian: "должен" },
  { english: "country", russian: "страна" },
  { english: "found", russian: "нашел" },
  { english: "answer", russian: "ответ" },
  { english: "school", russian: "школа" },
  { english: "grow", russian: "расти" },
  { english: "study", russian: "учеба" },
  { english: "still", russian: "все еще" },
  { english: "learn", russian: "учить" },
  { english: "plant", russian: "растение" },
  { english: "cover", russian: "покрытие" },
  { english: "food", russian: "еда" },
  { english: "sun", russian: "солнце" },
  { english: "four", russian: "четыре" },
  { english: "between", russian: "между" },
  { english: "state", russian: "состояние" },
  { english: "keep", russian: "держать" },
  { english: "never", russian: "никогда" },
  { english: "last", russian: "последний" },
  { english: "let", russian: "позволить" },
  { english: "thought", russian: "мысль" },
  { english: "city", russian: "город" },
  { english: "tree", russian: "дерево" },
  { english: "cross", russian: "пересекать" },
  { english: "farm", russian: "ферма" },
  { english: "hard", russian: "трудный" },
  { english: "start", russian: "начать" },
  { english: "might", russian: "мог бы" },
  { english: "story", russian: "история" },
  { english: "saw", russian: "увидел" },
  { english: "far", russian: "далеко" },
  { english: "sea", russian: "море" },
  { english: "draw", russian: "рисовать" },
  { english: "left", russian: "левый" },
  { english: "late", russian: "поздно" },
  { english: "run", russian: "бежать" },
  { english: "don’t", russian: "не" },
  { english: "while", russian: "пока" },
  { english: "press", russian: "нажать" },
  { english: "close", russian: "закрыть" },
  { english: "night", russian: "ночь" },
  { english: "real", russian: "реальный" },
  { english: "life", russian: "жизнь" },
  { english: "few", russian: "немного" },
  { english: "stop", russian: "остановить" },
  { english: "open", russian: "открыть" },
  { english: "seem", russian: "казаться" },
  { english: "together", russian: "вместе" },
  { english: "next", russian: "следующий" },
  { english: "white", russian: "белый" },
  { english: "children", russian: "дети" },
  { english: "begin", russian: "начать" },
  { english: "got", russian: "получил" },
  { english: "walk", russian: "идти" },
  { english: "example", russian: "пример" },
  { english: "ease", russian: "легкость" },
  { english: "paper", russian: "бумага" },
  { english: "often", russian: "часто" },
  { english: "music", russian: "музыка" },
  { english: "those", russian: "те" },
  { english: "both", russian: "оба" },
  { english: "mark", russian: "метка" },
  { english: "dog", russian: "собака" },
  { english: "seat", russian: "место" },
  { english: "end", russian: "конец" },
  { english: "face", russian: "лицо" },
  { english: "else", russian: "иначе" },
  { english: "quite", russian: "довольно" },
  { english: "check", russian: "проверить" },
  { english: "create", russian: "создавать" },
  { english: "speak", russian: "говорить" },
  { english: "add", russian: "добавить" },
  { english: "seven", russian: "семь" },
  { english: "should", russian: "должен" },
  { english: "class", russian: "класс" },
  { english: "why", russian: "почему" },
  { english: "become", russian: "стать" },
  { english: "short", russian: "короткий" },
  { english: "count", russian: "считать" },
  { english: "square", russian: "квадрат" },
  { english: "reason", russian: "причина" },
  { english: "length", russian: "длина" },
  { english: "represent", russian: "представлять" },
  { english: "art", russian: "искусство" },
  { english: "subject", russian: "предмет" },
  { english: "region", russian: "регион" },
  { english: "size", russian: "размер" },
  { english: "vary", russian: "различаться" },
  { english: "settle", russian: "поселиться" },
  { english: "sugar", russian: "сахар" },
  { english: "area", russian: "область" },
  { english: "activity", russian: "деятельность" },
  { english: "industry", russian: "промышленность" },
  { english: "nature", russian: "природа" },
  { english: "material", russian: "материал" },
  { english: "science", russian: "наука" },
  { english: "technology", russian: "технология" },
  { english: "development", russian: "развитие" },
  { english: "knowledge", russian: "знание" },
  { english: "information", russian: "информация" },
  { english: "government", russian: "правительство" },
  { english: "economy", russian: "экономика" },
  { english: "health", russian: "здоровье" },
  { english: "education", russian: "образование" },
  { english: "environment", russian: "окружающая среда" },
  { english: "community", russian: "сообщество" },
  { english: "society", russian: "общество" },
  { english: "culture", russian: "культура" },
  { english: "policy", russian: "политика" },
  { english: "system", russian: "система" },
  { english: "service", russian: "услуга" },
  { english: "quality", russian: "качество" },
  { english: "value", russian: "ценность" },
  { english: "power", russian: "власть" },
  { english: "relationship", russian: "отношение" },
  { english: "process", russian: "процесс" },
  { english: "goal", russian: "цель" },
  { english: "strategy", russian: "стратегия" },
  { english: "analysis", russian: "анализ" },
  { english: "project", russian: "проект" },
  { english: "method", russian: "метод" },
  { english: "result", russian: "результат" },
  { english: "solution", russian: "решение" },
  { english: "challenge", russian: "вызов" },
  { english: "success", russian: "успех" },
  { english: "failure", russian: "неудача" },
  { english: "experience", russian: "опыт" },
  { english: "skill", russian: "умение" },
  { english: "talent", russian: "талант" },
  { english: "creativity", russian: "креативность" },
  { english: "innovation", russian: "инновация" },
  { english: "research", russian: "исследование" },
  { english: "data", russian: "данные" },
  { english: "report", russian: "отчет" },
  { english: "presentation", russian: "презентация" },
  { english: "discussion", russian: "обсуждение" },
  { english: "debate", russian: "дебаты" },
  { english: "argument", russian: "аргумент" },
  { english: "conclusion", russian: "заключение" },
  { english: "summary", russian: "резюме" },
  { english: "recommendation", russian: "рекомендация" },
  { english: "feedback", russian: "обратная связь" },
  { english: "review", russian: "обзор" },
  { english: "evaluation", russian: "оценка" },
  { english: "assessment", russian: "оценка" },
  { english: "contribution", russian: "вклад" },
  { english: "collaboration", russian: "сотрудничество" },
  { english: "teamwork", russian: "командная работа" },
  { english: "leadership", russian: "лидерство" },
  { english: "motivation", russian: "мотивация" },
  { english: "inspiration", russian: "вдохновение" },
  { english: "passion", russian: "страсть" },
  { english: "dedication", russian: "посвящение" },
  { english: "commitment", russian: "обязанность" },
  { english: "responsibility", russian: "ответственность" },
  { english: "accountability", russian: "подотчетность" },
  { english: "integrity", russian: "целостность" },
  { english: "honesty", russian: "честность" },
  { english: "trust", russian: "доверие" },
  { english: "respect", russian: "уважение" },
  { english: "empathy", russian: "сопереживание" },
  { english: "compassion", russian: "сострадание" },
  { english: "kindness", russian: "доброта" },
  { english: "generosity", russian: "щедрость" },
  { english: "gratitude", russian: "благодарность" },
  { english: "forgiveness", russian: "прощение" },
  { english: "love", russian: "любовь" },
  { english: "friendship", russian: "дружба" },
  { english: "family", russian: "семья" },
  { english: "community", russian: "сообщество" },
  { english: "belonging", russian: "принадлежность" },
  { english: "support", russian: "поддержка" },
  { english: "care", russian: "забота" },
  { english: "nurture", russian: "воспитывать" },
  { english: "growth", russian: "рост" },
  { english: "development", russian: "развитие" },
  { english: "success", russian: "успех" },
  { english: "happiness", russian: "счастье" },
  { english: "contentment", russian: "удовлетворение" },
  { english: "fulfillment", russian: "выполнение" },
  { english: "balance", russian: "баланс" },
  { english: "well-being", russian: "благополучие" },
  { english: "well-being", russian: "благополучие" },
  { english: "achievement", russian: "достижение" },
  { english: "adventure", russian: "приключение" },
  { english: "advantage", russian: "преимущество" },
  { english: "advice", russian: "совет" },
  { english: "analysis", russian: "анализ" },
  { english: "approach", russian: "подход" },
  { english: "area", russian: "область" },
  { english: "argument", russian: "аргумент" },
  { english: "aspect", russian: "аспект" },
  { english: "association", russian: "ассоциация" },
  { english: "atmosphere", russian: "атмосфера" },
  { english: "attempt", russian: "попытка" },
  { english: "authority", russian: "власть" },
  { english: "balance", russian: "баланс" },
  { english: "benefit", russian: "выгода" },
  { english: "challenge", russian: "вызов" },
  { english: "character", russian: "характер" },
  { english: "choice", russian: "выбор" },
  { english: "communication", russian: "коммуникация" },
  { english: "community", russian: "сообщество" },
  { english: "competition", russian: "конкурс" },
  { english: "concept", russian: "концепция" },
  { english: "consequence", russian: "последствие" },
  { english: "consideration", russian: "рассмотрение" },
  { english: "contribution", russian: "вклад" },
  { english: "conversation", russian: "разговор" },
  { english: "cooperation", russian: "сотрудничество" },
  { english: "creativity", russian: "творчество" },
  { english: "decision", russian: "решение" },
  { english: "development", russian: "развитие" },
  { english: "difference", russian: "разница" },
  { english: "discussion", russian: "обсуждение" },
  { english: "education", russian: "образование" },
  { english: "effect", russian: "эффект" },
  { english: "effort", russian: "усилие" },
  { english: "emotion", russian: "эмоция" },
  { english: "experience", russian: "опыт" },
  { english: "failure", russian: "неудача" },
  { english: "feeling", russian: "чувство" },
  { english: "focus", russian: "фокус" },
  { english: "goal", russian: "цель" },
  { english: "growth", russian: "рост" },
  { english: "happiness", russian: "счастье" },
  { english: "impact", russian: "влияние" },
  { english: "importance", russian: "важность" },
  { english: "improvement", russian: "улучшение" },
  { english: "information", russian: "информация" },
  { english: "inspiration", russian: "вдохновение" },
  { english: "interest", russian: "интерес" },
  { english: "interaction", russian: "взаимодействие" },
  { english: "interpretation", russian: "интерпретация" },
  { english: "involvement", russian: "участие" },
  { english: "knowledge", russian: "знание" },
  { english: "leadership", russian: "лидерство" },
  { english: "learning", russian: "обучение" },
  { english: "method", russian: "метод" },
  { english: "motivation", russian: "мотивация" },
  { english: "opportunity", russian: "возможность" },
  { english: "performance", russian: "выступление" },
  { english: "perspective", russian: "перспектива" },
  { english: "planning", russian: "планирование" },
  { english: "potential", russian: "потенциал" },
  { english: "process", russian: "процесс" },
  { english: "progress", russian: "прогресс" },
  { english: "relationship", russian: "отношение" },
  { english: "responsibility", russian: "ответственность" },
  { english: "result", russian: "результат" },
  { english: "satisfaction", russian: "удовлетворение" },
  { english: "solution", russian: "решение" },
  { english: "success", russian: "успех" },
  { english: "support", russian: "поддержка" },
  { english: "teamwork", russian: "командная работа" },
  { english: "trust", russian: "доверие" },
  { english: "understanding", russian: "понимание" },
  { english: "value", russian: "ценность" },
  { english: "vision", russian: "видение" },
  { english: "well-being", russian: "благополучие" },
];

// Перемешиваем массив слов
function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

shuffleArray(words); // Перемешиваем массив слов

let currentWordIndex = 0;

function loadQuestion() {
  const word = words[currentWordIndex];
  const questionElement = document.getElementById("question");
  const optionsElement = document.getElementById("options");
  const resultElement = document.getElementById("result");

  questionElement.textContent = `Переведите слово: ${word.english}`;
  optionsElement.innerHTML = "";
  resultElement.textContent = "";

  const translations = words.map((w) => w.russian);
  const correctTranslation = word.russian;

  // Создаем три варианта ответа
  const options = [
    correctTranslation,
    ...getRandomTranslations(correctTranslation, translations),
  ].sort(() => Math.random() - 0.5);

  options.forEach((option) => {
    const div = document.createElement("div");
    div.textContent = option;
    div.className = "option";
    div.onclick = () => checkAnswer(option, correctTranslation);
    optionsElement.appendChild(div);
  });
}

function getRandomTranslations(correctTranslation, translations) {
  const filtered = translations.filter((t) => t !== correctTranslation);
  const randomTranslations = [];
  while (randomTranslations.length < 2) {
    const randomIndex = Math.floor(Math.random() * filtered.length);
    randomTranslations.push(filtered[randomIndex]);
    filtered.splice(randomIndex, 1);
  }
  return randomTranslations;
}

function checkAnswer(selected, correct) {
  const options = document.getElementsByClassName("option");
  const resultElement = document.getElementById("result");

  for (let option of options) {
    if (option.textContent === correct) {
      option.classList.add("correct");
    } else {
      option.classList.add("incorrect");
    }
  }

  if (selected === correct) {
    resultElement.textContent = "Правильно!";
  } else {
    resultElement.textContent = `Неправильно! Правильный ответ: ${correct}`;
  }

  currentWordIndex = (currentWordIndex + 1) % words.length;
  setTimeout(loadQuestion, 3000);
}

// Начинаем тест
loadQuestion();
